# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
  # valid drivers options include "gd" or "gmagick" or "imagick"
  driver: "gd"
  filter_sets:
    thumb:
      quality: 75
      filters:
        thumbnail: { size: [120, 90], mode: outbound }
        scale:
          dim: [250, 250]
    reduc_01:
      quality: 75
      filters:
        scale:
          dim: [250, 250]
        background:
          size: [300, 300]
          position: center
    reduc_02:
      quality: 75
      filters:
        scale:
          dim: [50, 50]
          position: center

    medium:
      quality: 75
      filters:
        thumbnail:
          size: [800, 530]
          mode: outbound
