vich_uploader:
  db_driver: orm

  mappings:
    article_photo:
      uri_prefix: /article/photo
      upload_destination: "%kernel.project_dir%/public/article/photo"
      # namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
